# -*- coding: utf-8 -*-
"""Dictonary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xg9BumDMPy6I-_SI0uLVfgKry6pSkR4_
"""

thisdict = {
  1: "Ford",
  2: "Mustang",
  4: 1964
}
thisdict[4]
#key has to be unique
thisdict[4]=2004
print(thisdict)
#dictonary is mutable

