# -*- coding: utf-8 -*-
"""list&Tuples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kGTiffRjmW81aSp1e1hQYG8SE6IfZPoI
"""

list1=[1,2,31,41,'hi']
print(list1[-2])
list1[4]
list1[-4]=100
print(list1)
print(list1[::-1])
#list is mutable[changable]
#reversible

# Tuples are immutable
tup=(1,2,3,4)
tup[0]
tup[::-1]
#reversible

