# -*- coding: utf-8 -*-
"""sets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x71qjwfoPGLHY9RXISHsmy4dePoHjMpK
"""

sets={2,5,6,'hi','apple',6}
print(sets)
#Ordered
#duplicates not allowed
#Cannot access it with index
#set is mutable

