# -*- coding: utf-8 -*-
"""Yhills1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-FWUwTibjmbOCqv-Ng5el6--GtJ_kVBh
"""

print('Hello world')
x=10.90
y=10
type(x)
type(y)

